#!/usr/bin/env python3
"""
07_peptide_synthesis_validator.py

Validation of peptide synthesis protocols using Raman and CD spectroscopy signatures.
Ensures correct torsion for therapeutic efficacy.

Morató de Dalmases, 2026
"""

import numpy as np
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
from constants import CONWAY_TORSION, ETA_GAMMA
from quaternion_algebra import qmul, qconj, qnorm, product_sequence

# ============================================================================
# AMINO ACID QUATERNIONS
# ============================================================================

AMINO_ACIDS = {
    'C': np.array([0.250, 0.250, 0.125, 0.375]),  # Cysteine
    'Y': np.array([0.750, 0.250, 0.375, 0.250]),  # Tyrosine
    'G': np.array([0.125, 0.125, 0.125, 0.125]),  # Glycine
    'D': np.array([0.375, 0.125, 0.250, 0.125]),  # Aspartic acid
    'W': np.array([0.875, 0.500, 0.250, 0.500]),  # Tryptophan
    'P': np.array([0.375, 0.125, 0.250, 0.125]),  # Proline
    'A': np.array([0.125, 0.250, 0.125, 0.250]),  # Alanine
    'E': np.array([0.500, 0.125, 0.375, 0.125]),  # Glutamic acid
    'K': np.array([0.625, 0.500, 0.375, 0.500]),  # Lysine
    'R': np.array([0.375, 0.375, 0.375, 0.375]),  # Arginine
    'H': np.array([0.375, 0.250, 0.500, 0.250]),  # Histidine
    'N': np.array([0.250, 0.125, 0.375, 0.125]),  # Asparagine
    'Q': np.array([0.500, 0.375, 0.250, 0.375]),  # Glutamine
    'F': np.array([0.750, 0.375, 0.125, 0.375]),  # Phenylalanine
    'I': np.array([0.625, 0.375, 0.125, 0.375]),  # Isoleucine
    'L': np.array([0.625, 0.250, 0.250, 0.250]),  # Leucine
    'V': np.array([0.500, 0.500, 0.125, 0.500]),  # Valine
    'M': np.array([0.500, 0.250, 0.125, 0.250]),  # Methionine
    'S': np.array([0.250, 0.250, 0.250, 0.250]),  # Serine
    'T': np.array([0.375, 0.375, 0.125, 0.375}),  # Threonine
}

# ============================================================================
# SPECTRAL SIGNATURES
# ============================================================================

@dataclass
class SpectralSignature:
    """Raman and CD spectral signatures for quality control."""
    raman_peak_s_ss: float = 510.0  # cm^{-1} - rigid disulfide
    raman_peak_c_s: float = 645.0   # cm^{-1} - cysteine
    raman_peak_tyr: float = 830.0   # cm^{-1} - tyrosine
    raman_peak_trp: float = 880.0   # cm^{-1} - tryptophan
    cd_peak_beta_turn: float = 215.0  # nm - β-turn from knot projection
    cd_peak_alpha_helix_1: float = 208.0  # nm
    cd_peak_alpha_helix_2: float = 222.0  # nm

# ============================================================================
# PEPTIDE VALIDATION
# ============================================================================

@dataclass
class PeptideValidation:
    """Results of peptide synthesis validation."""
    sequence: str
    torsion: float
    is_geometrically_active: bool
    raman_peaks: Dict[str, bool]
    cd_peaks: Dict[str, bool]
    purity: float
    molecular_weight: float
    expected_weight: float
    defects: List[str]

def compute_peptide_torsion(sequence: str) -> float:
    """
    Compute the torsion generated by a peptide sequence.
    
    Args:
        sequence: Amino acid sequence (one-letter code)
    
    Returns:
        Torsion in rad/Å
    """
    quaternions = []
    for aa in sequence.upper():
        if aa in AMINO_ACIDS:
            quaternions.append(AMINO_ACIDS[aa])
        else:
            return 0.0
    
    # Compute total product and derivative
    if len(quaternions) < 2:
        return 0.0
    
    total = product_sequence(quaternions)
    norm = qnorm(total)
    
    # Torsion is related to deviation from unit norm
    torsion = abs(1 - norm) * CONWAY_TORSION * 2
    
    return torsion

def validate_peptide_sequence(sequence: str, expected_torsion: float) -> PeptideValidation:
    """
    Validate a synthesized peptide sequence.
    
    Args:
        sequence: Amino acid sequence (one-letter code)
        expected_torsion: Expected torsion in rad/Å
    
    Returns:
        PeptideValidation with quality control results
    """
    computed_torsion = compute_peptide_torsion(sequence)
    torsion_error = abs(computed_torsion - expected_torsion)
    is_active = torsion_error < 0.05  # Within 0.05 rad/Å
    
    # Simulate Raman peaks
    raman_peaks = {
        '510 cm^{-1} (S-S)': 'C' in sequence and sequence.count('C') >= 2,
        '645 cm^{-1} (C-S)': 'C' in sequence,
        '830 cm^{-1} (Tyr)': 'Y' in sequence,
        '880 cm^{-1} (Trp)': 'W' in sequence,
    }
    
    # Simulate CD peaks
    cd_peaks = {
        '215 nm (β-turn)': 'G' in sequence and 'D' in sequence,
        '208 nm (α-helix)': False,  # Short peptides rarely form α-helices
        '222 nm (α-helix)': False,
    }
    
    # Calculate molecular weight (simplified)
    aa_weights = {
        'C': 121.16, 'Y': 181.19, 'G': 75.07, 'D': 133.10,
        'W': 204.23, 'P': 115.13, 'A': 89.09, 'E': 147.13,
        'K': 146.19, 'R': 174.20, 'H': 155.16, 'N': 132.12,
        'Q': 146.15, 'F': 165.19, 'I': 131.18, 'L': 131.18,
        'V': 117.15, 'M': 149.21, 'S': 105.09, 'T': 119.12,
    }
    
    expected_weight = sum(aa_weights.get(aa, 0) for aa in sequence) - 18 * (len(sequence) - 1)
    molecular_weight = expected_weight * (1 + np.random.normal(0, 0.001))  # Simulate measurement
    
    # Collect defects
    defects = []
    if not is_active:
        defects.append(f"Torsion mismatch: {computed_torsion:.3f} vs {expected_torsion:.3f} rad/Å")
    if not raman_peaks['510 cm^{-1} (S-S)']:
        defects.append("Missing disulfide bridge (no 510 cm^{-1} Raman peak)")
    if not cd_peaks['215 nm (β-turn)']:
        defects.append("Missing β-turn structure (no 215 nm CD peak)")
    
    return PeptideValidation(
        sequence=sequence,
        torsion=computed_torsion,
        is_geometrically_active=is_active and len(defects) == 0,
        raman_peaks=raman_peaks,
        cd_peaks=cd_peaks,
        purity=0.98,  # Assumed >98% purity
        molecular_weight=molecular_weight,
        expected_weight=expected_weight,
        defects=defects
    )

# ============================================================================
# MAIN VALIDATION
# ============================================================================

def validate_all_peptides():
    """Validate all designed Nanopor-Tap peptides."""
    print("=" * 70)
    print("PEPTIDE SYNTHESIS VALIDATION")
    print("Based on Conway Knot K11n34 Topology")
    print("Morató de Dalmases, 2026")
    print("=" * 70)
    
    peptides = [
        ("CYGDWC", 0.34, "KRAS G12D"),
        ("CYGDWPC", 0.41, "BRAF V600E"),
    ]
    
    for seq, expected_torsion, target in peptides:
        print(f"\n{target} - Sequence: {seq}")
        print("-" * 50)
        
        validation = validate_peptide_sequence(seq, expected_torsion)
        
        print(f"  Computed torsion: {validation.torsion:.3f} rad/Å")
        print(f"  Expected torsion: {expected_torsion:.3f} rad/Å")
        print(f"  Torsion error: {abs(validation.torsion - expected_torsion):.3f} rad/Å")
        print(f"  Geometrically active: {validation.is_geometrically_active}")
        
        print("\n  Raman Spectroscopy:")
        for peak, present in validation.raman_peaks.items():
            print(f"    {peak}: {'✓' if present else '✗'}")
        
        print("\n  Circular Dichroism:")
        for peak, present in validation.cd_peaks.items():
            print(f"    {peak}: {'✓' if present else '✗'}")
        
        print(f"\n  Molecular weight: {validation.molecular_weight:.1f} Da "
              f"(expected: {validation.expected_weight:.1f} Da)")
        print(f"  Purity: {validation.purity:.1%}")
        
        if validation.defects:
            print(f"\n  Defects:")
            for defect in validation.defects:
                print(f"    ✗ {defect}")
        else:
            print("\n  ✓ All quality control tests passed")
    
    print("\n" + "=" * 70)
    print("VALIDATION COMPLETE")
    print("=" * 70)

if __name__ == "__main__":
    validate_all_peptides()